### PR TITLE
Fix RGB <-> HSV conversion

### PR DESCRIPTION
**Pull request by nsamala**
I was having some issues with the RGB / HSV conversion so I re-implemented those constructors using https://gist.github.com/fairlight1337/4935ae72bcbcc1ba5c72

There is a breaking change: HSV now takes `uint16_t` for `hue`

### CODE REVIEW

**Comment by yaqwsx** [comment]
First, thank you for your contribution. Could you be more specific about the issues? Ideally give an example - maybe we can bugfix them.

I am not merging your changes in current state as they use floating point operations which is an unwanted feature (it is a serious performance hit when using large number of LEDs).

**Comment by nsamala** [comment]
I'll have to go back an reproduce the issues, but the challenges I was facing was that I'd get incorrect RGB colors from a given HSV value and vice versa. I'll see if I can give you something to reproduce.

And totally fair, when I saw that the original had floating point operations, I was a bit worried myself (but it does appear to work for my current use case).

**Comment by yaqwsx** [comment]
One thing I observe in your PR: you changed the hue range from 0-255 to 0-360. Is there a chance that you assumed the HSV values with hue in range 0-360 instead of 0-255?

**Comment by nsamala** [comment]
@yaqwsx that's entirely possible. I'll be sure to go back and double check

**Comment by yaqwsx** [comment]
Hi, I am sorry for the delay. You are right, the color conversions were totally off. I have never tested them properly - I only by looked at the LEDs and they seemed to be correct.

I have implemented a simple test and fixed the conversions. You can find it in a new branch NewColorConversion - https://github.com/RoboticsBrno/SmartLeds/tree/NewColorConversion

Could you please look at it and confirm it is correct?

**Comment by yaqwsx** [comment]
@nsamala: Did you looked at the proposed fix?

**Comment by nsamala** [comment]
Hey, yup I just verified it.. It's good to go now :)

**Comment by yaqwsx** [comment]
Ok, I merged the fix into the master branch.

**Pull request closed without merging**
